### ISSUE TITLE
url params missing in params hash

### ISSUE THREAD

**Issue by scauglog** [aserafin/grape_logging#27]
when there is url parameters like

``` Ruby
post "(:some_url)/test" do
 #some code here
end
```

there is no key "some_url" in the params hash.

**Comment by scauglog** [comment]
I can get it if i use `request.env["api.endpoint"].params.to_h` or `env["api.endpoint"].params.to_h` instead of `request.params`
I don't know if there is any edge case, so i have created a new "loggers" named url_params. Tell me if you prefer modify request_logger.rb instead.

**Comment by selcham** [comment]
Hi,
Same here, I tried your changes which seem to work fine.

**Comment by aserafin** [comment]
@scauglog do you declare you params also in `params` block like below or only in the url string?

```
params do
  requires :id, type: Integer
end 
get 'sth/:id' do 
end
```

**Comment by scauglog** [comment]
yes, I also declare my params in the params block

**Comment by migmartri** [comment]
Same problem here.

Currently I am using https://github.com/ridiculous/grape-middleware-logger which leverages the official Grape::Middleware::Globals to retrieve parameters.

[This is](https://github.com/ridiculous/grape-middleware-logger/blob/master/lib/grape/middleware/logger.rb#L85) how it reads the values pre-set by [this other middleware](https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/globals.rb#L7)

One solution would be to rely on `Grape::Request.new` (which [has an enhanced params](http://www.rubydoc.info/github/intridea/grape/Grape%2FRequest:params)) as you can see [here](https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/globals.rb#L7) instead of Rack.request as [this library](https://github.com/aserafin/grape_logging/blob/master/lib/grape_logging/middleware/request_logger.rb#L109) currently uses.  

Another solution is just to implement the parameters retrieval like in `ridiculous/grape-middleware-logger` although it will add the dependency on the global middleware.

What do you think.

**Comment by aserafin** [comment]
c
